export { default as NavBar} from './navbar';
export { default as HomeHero } from './home-hero';
export { default as PopularNow } from './popular-now';
export { default as DetailHero } from './detail-hero';
export { default as DetailCasts } from './detail-casts';
export { default as SearchForAll} from './search-section';
export { default as SearchHeader } from './search-header';
export { default as SearchMovies } from './search-movies';
export { default as SearchSeries } from './search-series';
export { default as SearchAside } from './search-aside';
export { default as TheatreMovies } from './theatre-movies';
export { default as TheatreTrailer } from './theatre-trailer';
export { default as UpcomingMovies } from './upcoming-movies';
export { default as UpcomingAllMovies } from './upcoming-all-movies';
export { default as Footer } from './footer';